name: Generate Podcast Feeds
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repo
       uses: actions/checkout@v3
     - name: Run Feed Genertaor
       uses: yashpatel3645/podcast-generator@main
